# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1d239248e84527ec0c218c54ecd477bed54dd654c9a3cf143f9ed6d19ccfdd4e009be71d09fe76f6f22062531e55324c16536da5037f77776335cda5d2ffcd

test:
  secret_key_base: db5159ba179da29bf10abe348e638da2fd95de199600f883bd485f3af7d10e43c6ac6679126e0a88ed35902a305797b8d2adcd0fb2b5031ad01534c3723e47bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
